name: "Code Style"

on: pull_request

jobs:
  SwiftFormat:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nicklockwood/swiftformat:0.54.3
    steps:
      - uses: actions/checkout@v4
      - run: ./tools/lint
