name: 'Code Style'

on: pull_request

jobs:
  SwiftFormat:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - run: swiftformat --cache ignore --lint --reporter github-actions-log --quiet .
