name: "Test"

on: push

env:
  # TODO: Load from `.swift-version` file
  SWIFT_VERSION: 6.1
  SWIFT_STATIC_SDK_URL: https://download.swift.org/swift-6.1-release/static-sdk/swift-6.1-RELEASE/swift-6.1-RELEASE_static-linux-0.0.1.artifactbundle.tar.gz
  SWIFT_STATIC_SDK_CHECKSUM: 111c6f7d280a651208b8c74c0521dd99365d785c1976a6e23162f55f65379ac6

jobs:
  ubuntu_x86_64:
    name: Release Linux x86_64
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Download Swift ${{ env.SWIFT_VERSION }}
        run: wget https://download.swift.org/swift-${{ env.SWIFT_VERSION }}-release/ubuntu2204/swift-${{ env.SWIFT_VERSION }}-RELEASE/swift-${{ env.SWIFT_VERSION }}-RELEASE-ubuntu22.04.tar.gz
      - name: Extract Swift ${{ env.SWIFT_VERSION }}
        run: tar xzf swift-${{ env.SWIFT_VERSION }}-RELEASE-ubuntu22.04.tar.gz
      - name: Add Swift toolchain to PATH
        run: echo "$GITHUB_WORKSPACE/swift-${{ env.SWIFT_VERSION }}-RELEASE-ubuntu22.04/usr/bin" >> $GITHUB_PATH
      - name: Package Linux x86_64
        run: make package-linux-x86_64
      - name: Upload Linux x86_64 Asset
        run: mv xcbeautify.tar.xz "xcbeautify-${{ env.TAG }}-x86_64-unknown-linux-gnu.tar.xz"

  ubuntu_x86_64_static:
    name: Release Linux x86_64 Static
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Download Swift ${{ env.SWIFT_VERSION }}
        run: wget https://download.swift.org/swift-${{ env.SWIFT_VERSION }}-release/ubuntu2204/swift-${{ env.SWIFT_VERSION }}-RELEASE/swift-${{ env.SWIFT_VERSION }}-RELEASE-ubuntu22.04.tar.gz
      - name: Extract Swift ${{ env.SWIFT_VERSION }}
        run: tar xzf swift-${{ env.SWIFT_VERSION }}-RELEASE-ubuntu22.04.tar.gz
      - name: Add Swift toolchain to PATH
        run: echo "$GITHUB_WORKSPACE/swift-${{ env.SWIFT_VERSION }}-RELEASE-ubuntu22.04/usr/bin" >> $GITHUB_PATH
      - name: Install Swift Static Linux SDK
        run: swift sdk install "${{ env.SWIFT_STATIC_SDK_URL }}" --checksum "${{ env.SWIFT_STATIC_SDK_CHECKSUM }}"
      - name: Package Linux x86_64 Static
        run: make package-linux-x86_64-static
      - name: Upload Linux x86_64 Static Asset
        run: mv xcbeautify.tar.xz "xcbeautify-${{ env.TAG }}-x86_64-linux-static.tar.xz"
